#ifndef ESP_SARA_CONFIG_H
#define ESP_SARA_CONFIG_H

#include "sdkconfig.h"
#include "driver/uart.h"

#define SARA_UART_BAUD 115200 //CONFIG_SARA_UART_BAUD
#define SARA_UART_TX_PIN  26//CONFIG_SARA_UART_TX_PIN
#define SARA_UART_RX_PIN 25 //CONFIG_SARA_UART_RX_PIN
#define SARA_UART_RTS_PIN 2 //CONFIG_SARA_UART_RTS_PIN
#define SARA_UART_DTR_PIN 14//CONFIG_SARA_UART_DTR_PIN

// #ifdef CONFIG_SARA_UART_USE_RTS
// #define SARA_UART_HW_CONTROL UART_HW_FLOWCTRL_RTS
// #elif CONFIG_SARA_UART_USE_CTS
// #define SARA_UART_HW_CONTROL UART_HW_FLOWCTRL_CTS
// #elif CONFIG_SARA_UART_USE_RTS_CTS
// #define SARA_UART_HW_CONTROL UART_HW_FLOWCTRL_CTS_RTS
// #elif CONFIG_SARA_UART_USE_MAX
// #define SARA_UART_HW_CONTROL UART_HW_FLOWCTRL_MAX
// #elif CONFIG_SARA_UART_USE_DISABLE
// #define SARA_UART_HW_CONTROL UART_HW_FLOWCTRL_DISABLE
// #else
#define SARA_UART_HW_CONTROL UART_HW_FLOWCTRL_DISABLE
// #endif

// #ifdef CONFIG_USE_UART_0
// #define SARA_UART_NUM UART_NUM_0
// #elif CONFIG_USE_UART_1
#define SARA_UART_NUM UART_NUM_1
// #else
// #define SARA_UART_NUM UART_NUM_0
// #endif

#define SARA_BUFFER_SIZE 1024 //CONFIG_SARA_BUFFER_SIZE

#endif /* ESP_SARA_CONFIG_H */